# Generated by Django 2.2.15 on 2022-11-04 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='callstruction', max_length=12)),
                ('phone', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2022, 11, 4, 16, 46, 54, 370157))),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='callstruction', max_length=12)),
                ('phone', models.CharField(max_length=10)),
                ('category', models.CharField(default='building', max_length=20)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2022, 11, 4, 16, 46, 54, 369093))),
            ],
        ),
    ]
