# Generated by Django 2.2.15 on 2022-11-04 16:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 16, 49, 7, 691723, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 16, 49, 7, 690681, tzinfo=utc)),
        ),
    ]
