# Generated by Django 2.2.15 on 2022-11-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0003_auto_20221104_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='category',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='description',
        ),
    ]
