# Generated by Django 2.2.15 on 2022-11-06 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0004_auto_20221104_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=10)),
                ('customer_name', models.CharField(default='customer', max_length=20)),
                ('amount', models.BigIntegerField()),
                ('action', models.CharField(choices=[('consult', 'Consult'), ('booking', 'Booking')], default='consult', max_length=20)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='category',
        ),
        migrations.AddField(
            model_name='consultation',
            name='categphone',
            field=models.CharField(default='building', max_length=20),
        ),
    ]
