# Generated by Django 2.2.15 on 2022-11-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0006_auto_20221106_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total_collected',
            field=models.BigIntegerField(default=0),
        ),
    ]
